### ISSUE TITLE
使用效果怎么样？

### ISSUE THREAD

**Issue by yzqt** [taoweiji/GradleKotlinSpringBootMybatisSQLiteDemo#1]
请问？实际使用效果和原来的相比有那些好处呢？

**Comment by taoweiji** [comment]
SQLite其实不建议在生产环境使用，可以在测试环境作为轻量级数据库使用。
Kotlin语言很好看，现在我的项目已经全面转向Kotlin了。
Spring Boot也是很好用，很轻量级。
